"""Memory file manager for MathTutor-RL student profiles.

Manages four persistent data stores per student:

  USER.md        — static profile: goals, grade level, explanation style
  MEMORY.md      — dynamic KC mastery scores (BKT state)
  YYYY-MM-DD.md  — daily session log: attempts, hints, corrections, rewards
  .learnings/    — pending behaviour patterns; promoted by daily cron

All files live under ``{memory_dir}/{student_id}/``.
The memory_dir defaults to ``MATH_TUTOR_MEMORY_DIR`` env-var or ``./math_tutor_memory``.
"""

from __future__ import annotations

import json
import logging
import os
import re
import time
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Optional

logger = logging.getLogger(__name__)

_DEFAULT_MEMORY_DIR = os.getenv("MATH_TUTOR_MEMORY_DIR", "./math_tutor_memory")


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _today() -> str:
    return datetime.now(tz=timezone.utc).strftime("%Y-%m-%d")


def _now_str() -> str:
    return datetime.now(tz=timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")


def _student_dir(base_dir: str, student_id: str) -> Path:
    d = Path(base_dir) / student_id
    d.mkdir(parents=True, exist_ok=True)
    return d


def _safe_write(path: Path, content: str) -> None:
    tmp = path.with_suffix(path.suffix + ".tmp")
    try:
        tmp.write_text(content, encoding="utf-8")
        tmp.replace(path)
    except OSError as exc:
        logger.warning("[MemoryManager] failed to write %s: %s", path, exc)


def _safe_read(path: Path, default: str = "") -> str:
    try:
        return path.read_text(encoding="utf-8")
    except FileNotFoundError:
        return default
    except OSError as exc:
        logger.warning("[MemoryManager] failed to read %s: %s", path, exc)
        return default


# ---------------------------------------------------------------------------
# USER.md
# ---------------------------------------------------------------------------

_USER_TEMPLATE = """\
# Student Profile

- Goals: {goals}
- Grade Level: {grade_level}
- Explanation Style: {style}
- Native Language: {language}
- Created: {created}
"""


def load_user_profile(base_dir: str, student_id: str) -> dict:
    """Return a dict with keys: goals, grade_level, style, language."""
    path = _student_dir(base_dir, student_id) / "USER.md"
    text = _safe_read(path)
    profile: dict[str, str] = {
        "goals": "general math improvement",
        "grade_level": "high school",
        "style": "detailed",
        "language": "English",
    }
    if not text:
        return profile

    for line in text.splitlines():
        if m := re.match(r"-\s*Goals:\s*(.+)", line):
            profile["goals"] = m.group(1).strip()
        elif m := re.match(r"-\s*Grade Level:\s*(.+)", line):
            profile["grade_level"] = m.group(1).strip()
        elif m := re.match(r"-\s*Explanation Style:\s*(.+)", line):
            profile["style"] = m.group(1).strip()
        elif m := re.match(r"-\s*Native Language:\s*(.+)", line):
            profile["language"] = m.group(1).strip()
    return profile


def save_user_profile(
    base_dir: str,
    student_id: str,
    goals: str = "general math improvement",
    grade_level: str = "high school",
    style: str = "detailed",
    language: str = "English",
) -> None:
    path = _student_dir(base_dir, student_id) / "USER.md"
    _safe_write(
        path,
        _USER_TEMPLATE.format(
            goals=goals,
            grade_level=grade_level,
            style=style,
            language=language,
            created=_now_str(),
        ),
    )
    logger.info("[MemoryManager] USER.md saved for student=%s", student_id)


# ---------------------------------------------------------------------------
# MEMORY.md  (BKT mastery scores)
# ---------------------------------------------------------------------------

_MEMORY_HEADER = """\
# Knowledge Component Mastery
<!-- Auto-generated by MathTutor-RL. Do not edit manually. -->
<!-- Last updated: {updated} -->

## Summary
- Total KCs tracked: {total_kcs}
- KCs in ZPD [0.40–0.70]: {zpd_kcs}

"""

_MEMORY_TABLE_HEADER = """\
| KC | Category | Mastery | Attempts | Correct | Last Updated |
|---|---|---|---|---|---|
"""


def save_memory(
    base_dir: str,
    student_id: str,
    bkt_model,               # BKTStudentModel instance
    session_count: int = 0,
) -> None:
    """Write MEMORY.md from the current BKT state."""
    from bkt_student_model import ZPD_LO, ZPD_HI
    from kc_tagger import KC_CATEGORIES

    path = _student_dir(base_dir, student_id) / "MEMORY.md"
    now = _now_str()
    all_kcs = bkt_model.to_dict().get("kcs", {})
    zpd_count = sum(1 for v in all_kcs.values() if ZPD_LO <= v["p_mastery"] <= ZPD_HI)

    lines = [
        _MEMORY_HEADER.format(
            updated=now,
            total_kcs=len(all_kcs),
            zpd_kcs=zpd_count,
        ),
        _MEMORY_TABLE_HEADER,
    ]

    for kc_id, kc_data in sorted(all_kcs.items()):
        category = KC_CATEGORIES.get(kc_id, "?")
        mastery = kc_data["p_mastery"]
        attempts = kc_data["attempts"]
        correct = kc_data["correct"]
        lines.append(
            f"| {kc_id} | {category} | {mastery:.3f} | {attempts} | {correct} | {now} |\n"
        )

    _safe_write(path, "".join(lines))
    logger.info("[MemoryManager] MEMORY.md saved for student=%s (%d KCs)", student_id, len(all_kcs))


def load_memory(base_dir: str, student_id: str):
    """Load BKT model from MEMORY.md. Returns a new BKTStudentModel."""
    from bkt_student_model import BKTStudentModel, KCState

    path = _student_dir(base_dir, student_id) / "MEMORY.md"
    text = _safe_read(path)
    if not text:
        return BKTStudentModel()

    model = BKTStudentModel()
    # Parse the markdown table rows (skip header lines)
    for line in text.splitlines():
        m = re.match(
            r"\|\s*(\w+)\s*\|[^|]*\|\s*([\d.]+)\s*\|\s*(\d+)\s*\|\s*(\d+)\s*\|",
            line,
        )
        if m:
            kc_id = m.group(1)
            p_mastery = float(m.group(2))
            attempts = int(m.group(3))
            correct = int(m.group(4))
            kc_state = KCState(p_mastery=p_mastery, attempts=attempts, correct=correct)
            model.add_kc_state(kc_id, kc_state)
    return model


# ---------------------------------------------------------------------------
# YYYY-MM-DD.md  (daily session log)
# ---------------------------------------------------------------------------

def log_session_start(base_dir: str, student_id: str, session_id: str) -> None:
    """Append a session-start entry to today's log file."""
    path = _student_dir(base_dir, student_id) / f"{_today()}.md"
    exists = path.exists()
    with path.open("a", encoding="utf-8") as f:
        if not exists:
            f.write(f"# Session Log: {_today()}\n\n")
        f.write(f"\n## Session: {session_id}\nStarted: {_now_str()}\n\n")


def log_turn_event(
    base_dir: str,
    student_id: str,
    session_id: str,
    turn_num: int,
    reward: dict,
    kc: Optional[str],
    correct: Optional[bool],
    hint_given: bool,
) -> None:
    """Append a turn event to today's session log."""
    path = _student_dir(base_dir, student_id) / f"{_today()}.md"
    parts = [f"- Turn {turn_num}: reward={reward.get('score', 0.0):.3f}"]
    if kc:
        parts.append(f"kc={kc}")
    if correct is not None:
        parts.append("correct" if correct else "incorrect")
    if hint_given:
        parts.append("hint_given")
    line = ", ".join(parts)
    with path.open("a", encoding="utf-8") as f:
        f.write(line + "\n")


def log_session_end(
    base_dir: str,
    student_id: str,
    session_id: str,
    total_turns: int,
    avg_reward: float,
) -> None:
    """Append a session-end summary to today's log."""
    path = _student_dir(base_dir, student_id) / f"{_today()}.md"
    with path.open("a", encoding="utf-8") as f:
        f.write(
            f"Ended: {_now_str()}, total_turns={total_turns}, avg_reward={avg_reward:.3f}\n"
        )


# ---------------------------------------------------------------------------
# .learnings/  (pending behaviour patterns)
# ---------------------------------------------------------------------------

def record_learning_pattern(
    base_dir: str,
    student_id: str,
    pattern: dict,
) -> None:
    """Append a learning pattern to .learnings/ as a JSON line.

    Patterns are keyed by (session_id, kc_id, error_type).
    A daily cron job can inspect these and promote stable patterns back
    into MEMORY.md or USER.md.
    """
    learnings_dir = _student_dir(base_dir, student_id) / ".learnings"
    learnings_dir.mkdir(exist_ok=True)
    path = learnings_dir / f"{_today()}.jsonl"
    record = {
        "timestamp": _now_str(),
        **pattern,
    }
    with path.open("a", encoding="utf-8") as f:
        f.write(json.dumps(record, ensure_ascii=False) + "\n")


def promote_learnings(base_dir: str, student_id: str, min_count: int = 3) -> list[dict]:
    """Scan .learnings/ files and return patterns that appear ≥ min_count times.

    Callers can use the returned patterns to update MEMORY.md or USER.md.
    """
    learnings_dir = _student_dir(base_dir, student_id) / ".learnings"
    if not learnings_dir.exists():
        return []

    pattern_counts: dict[str, dict[str, Any]] = {}
    for jl_path in sorted(learnings_dir.glob("*.jsonl")):
        for line in _safe_read(jl_path).splitlines():
            try:
                rec = json.loads(line)
                key = f"{rec.get('kc_id', '?')}::{rec.get('error_type', '?')}"
                if key not in pattern_counts:
                    pattern_counts[key] = {"count": 0, **rec}
                pattern_counts[key]["count"] += 1
            except (json.JSONDecodeError, KeyError):
                pass

    return [v for v in pattern_counts.values() if v["count"] >= min_count]
